[pytest]
testpaths = app/test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --tb=short
    -v
    --disable-warnings
    --ignore=app/test/test_kafka_direct.py
    --ignore=app/test/test_kafka_producer.py
    --ignore=app/test/test_run_kafka_pipeline.py
markers =
    integration: marks tests as integration tests
    unit: marks tests as unit tests
    slow: marks tests as slow
norecursedirs = .git .venv venv __pycache__ *.egg-info migrations
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::pytest.PytestUnknownMarkWarning
