export {
  api,
  registerUser,
  loginUser,
  logoutUser,
  checkAuth,
  ProfileData,
  fetchFileTypes,
  testApiUrl,
  getEscalation,
  getTrending,
  getTensionIndex,
  getPredictions,
  createPrediction,
  votePrediction,
  getNewsFeed,
  getMarketData,
} from './api';
